### ISSUE TITLE
NPM Package?

### ISSUE THREAD

**Issue by OhadRau** [reasonml-community/bs-socket.io#8]
I couldn't find a package for this on NPM. I think that would simplify usage with most Bucklescript projects, so is there any way someone could make an NPM port for this?

**Comment by graforlock** [comment]
its under `reasonml-community/bs-socket.io`

**Comment by remithomas** [comment]
@johnhaley81 you can install using direct link 

`npm install https://github.com/reasonml-community/bs-socket.io.git` or 
`yarn add https://github.com/reasonml-community/bs-socket.io.git`
